name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Generate config.js with secret
        run: |
          mkdir -p js
          echo "export const API_KEY = '${{ secrets.API_KEY }}';" > js/config.js
          echo "----- config.js content -----"
          cat js/config.js
          echo "-----------------------------"
          ls -l js

          grep -v '^config.js$' .gitignore > .gitignore.deploy
          mv .gitignore.deploy .gitignore
          echo "----- .gitignore.deploy content -----"
          cat .gitignore.deploy
          echo "-----------------------------"
          ls -l ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
